name: Main Build

on:
  push:
    branches:
      - publish-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Install dependencies
        run: |
          dotnet nuget add source --username USERNAME --password ${{ secrets.GH_FULL_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/mindbox-cloud/index.json"
          dotnet restore
      - name: Build
        run: dotnet build ./Mindbox.ExceptionsHandling.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore
      - name: Pack
        run: dotnet pack ./Mindbox.ExceptionsHandling.sln -c Release -p:BuildNumber=${{ github.run_number }} -p:VersionTag="-dev"
      - name: Publish
        run: dotnet nuget push **/*.nupkg -k ${{ secrets.GH_FULL_TOKEN }} -s "https://nuget.pkg.github.com/mindbox-cloud/index.json"
